# Generated by Django 5.1.7 on 2025-03-18 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['related_object_id', 'related_object_type'], name='notificatio_related_e0a5d0_idx'),
        ),
    ]
