# Generated by Django 5.1.7 on 2025-03-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_add_database_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Start'), ('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled'), ('sold', 'Sold')], default='draft', max_length=20),
        ),
    ]
