# Generated by Django 5.1.6 on 2025-03-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_fix_bid_status_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='min_bid_increment',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Minimum increment amount for bids', max_digits=12),
        ),
    ]
