# Generated by Django 5.1.7 on 2025-03-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.DeleteModel(
            name='AccountBalance',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
