# Generated by Django 5.1.7 on 2025-03-18 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_wallet_held_balance_wallet_pending_balance'),
        ('transactions', '0003_disable_payment_notification_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autobid',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='transactionlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='external_id',
        ),
        migrations.AlterField(
            model_name='autobid',
            name='bid_increment',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Amount to increment each automatic bid by', max_digits=8),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('purchase', 'Purchase'), ('sale', 'Sale'), ('fee', 'Platform Fee'), ('refund', 'Refund'), ('bid_hold', 'Bid Hold'), ('bid_release', 'Bid Release')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='action',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_type'], name='transaction_user_id_98a6b3_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'created_at'], name='transaction_status_d2f80b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference_id'], name='transaction_referen_1bb812_idx'),
        ),
    ]
