# Generated by Django 5.1.7 on 2025-03-18 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_disable_payment_notification_trigger'),
        ('transactions', '0004_alter_autobid_options_alter_transactionlog_options_and_more'),
    ]

    operations = [
    ]
