# Generated by Django 5.1.7 on 2025-03-09 22:16

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[apps.accounts.models.validate_phone_number], verbose_name='phone number'),
        ),
    ]
