# Generated by Django 5.1.7 on 2025-03-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_uuid_extension'),
        ('accounts', '0002_alter_user_phone_number'),
    ]

    operations = [
    ]
