# Generated by Django 5.1.7 on 2025-03-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='held_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='wallet',
            name='pending_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
